spring:
  flyway:
    enabled: true
  jpa:
    show-sql: false
  config:
    import: ""

logging:
  level:
    root: WARN
    bo.ucb.sport: INFO
    org.springframework.security: WARN
    org.flywaydb: WARN
    org.hibernate: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never
